version: '3'

services:
  # Tomcat service
  app:
    image: tomcat:10.1
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - ./build/libs/election-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/app.war
    depends_on:
      - postgres

  # PostgreSQL service
  postgres:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
